name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on:
  push:
    branches:
      - master

jobs:
  build-n-publish:
    name: ${{ matrix.os }} - ${{ matrix.python-version}} - Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI

    strategy:
      matrix:
        python-version: [ '2.x', '3.x', 'pypy-2.7', 'pypy-3.6', 'pypy-3.7' ]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        # Always clone the full depth so git-describe works.
        fetch-depth: 0
        submodules: true

    - name: Set up Python 🐍 ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

#    - name: Get full Python 🐍 version
#      id: full-python-version
#      run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

#    - name: Get repo version
#      run: echo ::set-output name=repo-version::$(python -c "import setup; print(setup.version_str)")

    - name: Install build dependencies
      run: |
        pip install -U pip
        pip install -U setuptools wheel twine

    - name: Install package dependencies
      run: |
        python setup.py install

    - name: Run smoke test
      run: |
        python test.py

    - name: Build distribution 📦
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish to Test PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        twine upload --repository testpypi dist/*

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload testpypi dist/*
